"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


AgentHandoffEntryObject = Literal["entry"]

AgentHandoffEntryType = Literal["agent.handoff"]


class AgentHandoffEntryTypedDict(TypedDict):
    previous_agent_id: str
    previous_agent_name: str
    next_agent_id: str
    next_agent_name: str
    object: NotRequired[AgentHandoffEntryObject]
    type: NotRequired[AgentHandoffEntryType]
    created_at: NotRequired[datetime]
    completed_at: NotRequired[Nullable[datetime]]
    id: NotRequired[str]


class AgentHandoffEntry(BaseModel):
    previous_agent_id: str

    previous_agent_name: str

    next_agent_id: str

    next_agent_name: str

    object: Optional[AgentHandoffEntryObject] = "entry"

    type: Optional[AgentHandoffEntryType] = "agent.handoff"

    created_at: Optional[datetime] = None

    completed_at: OptionalNullable[datetime] = UNSET

    id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"object", "type", "created_at", "completed_at", "id"}
        nullable_fields = {"completed_at"}
        null_default_fields = set()

        serialized = handler(self)
        m = {}
        model_fields = type(self).model_fields

        fields_set = self.__pydantic_fields_set__

        # Pre-calculate which fields are optional and optional_nullable for fast lookup
        optional_nullable_fields = optional_fields & nullable_fields

        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.pop(k, None)

            # This is set iff the field is in fields_set or in null_default_fields
            is_set = n in fields_set or k in null_default_fields

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL:
                # Perform using precomputed sets for lookup speed
                if k not in optional_fields or (
                    k in optional_nullable_fields and is_set
                ):
                    m[k] = val

        return m
