"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


AgentConversationObject = Literal["conversation"]


class AgentConversationTypedDict(TypedDict):
    id: str
    created_at: datetime
    updated_at: datetime
    agent_id: str
    name: NotRequired[Nullable[str]]
    r"""Name given to the conversation."""
    description: NotRequired[Nullable[str]]
    r"""Description of the what the conversation is about."""
    object: NotRequired[AgentConversationObject]


class AgentConversation(BaseModel):
    id: str

    created_at: datetime

    updated_at: datetime

    agent_id: str

    name: OptionalNullable[str] = UNSET
    r"""Name given to the conversation."""

    description: OptionalNullable[str] = UNSET
    r"""Description of the what the conversation is about."""

    object: Optional[AgentConversationObject] = "conversation"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields_set = {"name", "description", "object"}
        nullable_fields_set = {"name", "description"}
        null_default_fields_set = set()

        serialized = handler(self)
        m = {}

        # Precompute intersections for the whole set of fields set for efficient lookups
        fields_set = self.__pydantic_fields_set__

        # Store model_fields.items locally for faster lookup
        model_fields_items = type(self).model_fields.items()

        for n, f in model_fields_items:
            k = f.alias or n
            # Use pop only if value exists, otherwise fallback directly to None without scanning twice
            val = serialized.pop(k, None)

            # Combined field property checks
            optional_nullable = k in optional_fields_set and k in nullable_fields_set
            is_set = n in fields_set or k in null_default_fields_set  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields_set or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
