"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .file import File, FileTypedDict
from .timestampgranularity import TimestampGranularity
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from mistralai.utils import FieldMetadata, MultipartFormMetadata, validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AudioTranscriptionRequestTypedDict(TypedDict):
    model: str
    file: NotRequired[FileTypedDict]
    file_url: NotRequired[Nullable[str]]
    r"""Url of a file to be transcribed"""
    file_id: NotRequired[Nullable[str]]
    r"""ID of a file uploaded to /v1/files"""
    language: NotRequired[Nullable[str]]
    r"""Language of the audio, e.g. 'en'. Providing the language can boost accuracy."""
    temperature: NotRequired[Nullable[float]]
    stream: Literal[False]
    timestamp_granularities: NotRequired[List[TimestampGranularity]]
    r"""Granularities of timestamps to include in the response."""


class AudioTranscriptionRequest(BaseModel):
    model: Annotated[str, FieldMetadata(multipart=True)]

    file: Annotated[
        Optional[File], FieldMetadata(multipart=MultipartFormMetadata(file=True))
    ] = None

    file_url: Annotated[OptionalNullable[str], FieldMetadata(multipart=True)] = UNSET
    r"""Url of a file to be transcribed"""

    file_id: Annotated[OptionalNullable[str], FieldMetadata(multipart=True)] = UNSET
    r"""ID of a file uploaded to /v1/files"""

    language: Annotated[OptionalNullable[str], FieldMetadata(multipart=True)] = UNSET
    r"""Language of the audio, e.g. 'en'. Providing the language can boost accuracy."""

    temperature: Annotated[OptionalNullable[float], FieldMetadata(multipart=True)] = (
        UNSET
    )

    STREAM: Annotated[
        Annotated[Optional[Literal[False]], AfterValidator(validate_const(False))],
        pydantic.Field(alias="stream"),
        FieldMetadata(multipart=True),
    ] = False

    timestamp_granularities: Annotated[
        Optional[List[TimestampGranularity]], FieldMetadata(multipart=True)
    ] = None
    r"""Granularities of timestamps to include in the response."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Constants for fast lookup: convert lists to sets for O(1) membership testing
        optional_fields_set = {
            "file",
            "file_url",
            "file_id",
            "language",
            "temperature",
            "stream",
            "timestamp_granularities",
        }
        nullable_fields_set = {"file_url", "file_id", "language", "temperature"}
        null_default_fields_set = set()  # remains empty as in original

        serialized = handler(self)

        m = {}

        fields_set = self.__pydantic_fields_set__  # pylint: disable=no-member
        model_fields = type(self).model_fields

        # Avoid repeated lookups and allocation in loop: precompute which fields are both optional and nullable
        optional_nullable_fields = optional_fields_set & nullable_fields_set

        # Use .items() directly; avoid repeated get/pop calls by saving alias lookup
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.pop(
                k, None
            )  # Do pop right away; also covers .get(k) usage

            optional_nullable = k in optional_nullable_fields

            # Use set intersection boolean directly, no need to allocate intermediate set object
            is_set = (n in fields_set) or (k in null_default_fields_set)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields_set or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
