"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apiendpoint import APIEndpoint
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from mistralai.utils import validate_open_enum
from pydantic import model_serializer
from pydantic.functional_validators import PlainValidator
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BatchJobInTypedDict(TypedDict):
    input_files: List[str]
    endpoint: APIEndpoint
    model: NotRequired[Nullable[str]]
    agent_id: NotRequired[Nullable[str]]
    metadata: NotRequired[Nullable[Dict[str, str]]]
    timeout_hours: NotRequired[int]


class BatchJobIn(BaseModel):
    input_files: List[str]

    endpoint: Annotated[APIEndpoint, PlainValidator(validate_open_enum(False))]

    model: OptionalNullable[str] = UNSET

    agent_id: OptionalNullable[str] = UNSET

    metadata: OptionalNullable[Dict[str, str]] = UNSET

    timeout_hours: Optional[int] = 24

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Convert lists to sets for faster membership tests
        optional_fields = {"model", "agent_id", "metadata", "timeout_hours"}
        nullable_fields = {"model", "agent_id", "metadata"}
        null_default_fields = set()

        serialized = handler(self)
        m = {}

        # Precompute fields_set for faster lookup
        fields_set = self.__pydantic_fields_set__

        model_fields = type(self).model_fields

        # Avoid repeated lookups and redundant dict mutation
        # Use list(model_fields.items()) to avoid dictionary size change during iteration if that could arise
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            # Avoid popping from serialized, as it is not required for logic or performance
            optional_nullable = k in optional_fields and k in nullable_fields
            # Use 'n in fields_set' rather than intersection (much faster)
            is_set = (n in fields_set) or (k in null_default_fields)  # pylint: disable=no-member

            # Use identity comparisons and skip redundant checks (val != UNSET_SENTINEL implies val is not None, except for optimizations)
            if val is not None and val is not UNSET_SENTINEL:
                m[k] = val
            elif val is not UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
