"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ClassifierTrainingParametersTypedDict(TypedDict):
    training_steps: NotRequired[Nullable[int]]
    learning_rate: NotRequired[float]
    weight_decay: NotRequired[Nullable[float]]
    warmup_fraction: NotRequired[Nullable[float]]
    epochs: NotRequired[Nullable[float]]
    seq_len: NotRequired[Nullable[int]]


class ClassifierTrainingParameters(BaseModel):
    training_steps: OptionalNullable[int] = UNSET

    learning_rate: Optional[float] = 0.0001

    weight_decay: OptionalNullable[float] = UNSET

    warmup_fraction: OptionalNullable[float] = UNSET

    epochs: OptionalNullable[float] = UNSET

    seq_len: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Precompute sets for faster membership testing
        optional_fields = {
            "training_steps",
            "learning_rate",
            "weight_decay",
            "warmup_fraction",
            "epochs",
            "seq_len",
        }
        nullable_fields = {
            "training_steps",
            "weight_decay",
            "warmup_fraction",
            "epochs",
            "seq_len",
        }
        null_default_fields = set()  # Remains a set for lookup, even if empty

        serialized = handler(self)

        m = {}

        # Precompute intersection of fields set, used in loop below
        fields_set = self.__pydantic_fields_set__  # pylint: disable=no-member

        model_fields = type(self).model_fields

        # Avoid repeated lookups and computations in loop; minimize allocations
        for n, f in model_fields.items():
            k = f.alias or n
            # Only do one lookup in `serialized`
            val = serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            # is_set will be True if n is in fields_set or k in null_default_fields
            is_set = n in fields_set or k in null_default_fields

            # Fast-path common cases first
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
