"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ftclassifierlossfunction import FTClassifierLossFunction
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ClassifierTargetInTypedDict(TypedDict):
    name: str
    labels: List[str]
    weight: NotRequired[float]
    loss_function: NotRequired[Nullable[FTClassifierLossFunction]]


class ClassifierTargetIn(BaseModel):
    name: str

    labels: List[str]

    weight: Optional[float] = 1

    loss_function: OptionalNullable[FTClassifierLossFunction] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"weight", "loss_function"}
        nullable_fields = {"loss_function"}
        null_default_fields = set()

        serialized = handler(self)
        m = {}

        # Precompute fields for lookups and reuse
        model_fields = type(self).model_fields
        fields_set = self.__pydantic_fields_set__  # pylint: disable=no-member

        # Avoid .get() and then .pop(); pop once with default None
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.pop(k, None)

            # Use set logic for dramatically faster lookups
            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = n in fields_set or k in null_default_fields

            # The logic below is unchanged, but avoids redundant lookups and uses more efficient sets
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
