"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contentchunk import ContentChunk, ContentChunkTypedDict
from .toolcall import ToolCall, ToolCallTypedDict
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


ContentTypedDict = TypeAliasType(
    "ContentTypedDict", Union[str, List[ContentChunkTypedDict]]
)


Content = TypeAliasType("Content", Union[str, List[ContentChunk]])


class DeltaMessageTypedDict(TypedDict):
    role: NotRequired[Nullable[str]]
    content: NotRequired[Nullable[ContentTypedDict]]
    tool_calls: NotRequired[Nullable[List[ToolCallTypedDict]]]


class DeltaMessage(BaseModel):
    role: OptionalNullable[str] = UNSET

    content: OptionalNullable[Content] = UNSET

    tool_calls: OptionalNullable[List[ToolCall]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"role", "content", "tool_calls"}
        nullable_fields = {"role", "content", "tool_calls"}
        null_default_fields = set()

        serialized = handler(self)
        m = {}

        model_fields_items = type(self).model_fields.items()
        pydantic_fields_set = self.__pydantic_fields_set__

        for n, f in model_fields_items:
            k = f.alias or n
            val = serialized.get(k)

            # Don't pop from serialized dict (was unused result)
            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = n in pydantic_fields_set or k in null_default_fields  # pylint: disable=no-member

            # Compare val only once, avoid redundant checks
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL:
                if k not in optional_fields or (optional_nullable and is_set):
                    m[k] = val

        return m
