"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


DocumentURLChunkType = Literal["document_url"]


class DocumentURLChunkTypedDict(TypedDict):
    document_url: str
    document_name: NotRequired[Nullable[str]]
    r"""The filename of the document"""
    type: NotRequired[DocumentURLChunkType]


class DocumentURLChunk(BaseModel):
    document_url: str

    document_name: OptionalNullable[str] = UNSET
    r"""The filename of the document"""

    type: Optional[DocumentURLChunkType] = "document_url"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"document_name", "type"}
        nullable_fields = {"document_name"}
        null_default_fields = set()

        serialized = handler(self)

        m = {}

        # Precompute all keys needed for performance. Avoid type(self).model_fields.items() rebuild
        model_fields_items = type(self).model_fields.items()
        fields_set = self.__pydantic_fields_set__

        # Cached checks for intersection
        for n, f in model_fields_items:
            k = f.alias or n
            val = serialized.get(k)
            # Avoid pop as it can be expensive for large dicts. Just get.
            # The popping has no effect outside this local serialized; safe to skip.

            optional_nullable = k in optional_fields and k in nullable_fields
            # Use direct set membership test instead of set.intersection for singletons
            is_set = n in fields_set or k in null_default_fields  # pylint: disable=no-member

            # Use local assignment to avoid repeated attribute lookup
            # Only assign if field is set and not UNSET_SENTINEL
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
