"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class DocumentUpdateInTypedDict(TypedDict):
    name: NotRequired[Nullable[str]]


class DocumentUpdateIn(BaseModel):
    name: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Use constants (tuples) for fields for faster "in" checks
        optional_fields = ("name",)
        nullable_fields = ("name",)
        null_default_fields = set()  # using set for fast lookup

        serialized = handler(self)

        # Pre-allocate keys for performance instead of popping in place
        result = {}
        model_fields = type(self).model_fields
        # Store the intersection ONCE for reuse; saves repeated intersection calls
        pydantic_fields_set = self.__pydantic_fields_set__

        for n, f in model_fields.items():
            k = f.alias or n
            # Use .get to avoid KeyError, and pop once only if present
            val = serialized.get(k)
            if k in serialized:
                serialized.pop(k)

            optional_nullable = k in optional_fields and k in nullable_fields
            # precalc is_set: only call intersection once per field
            is_set = n in pydantic_fields_set or k in null_default_fields
            if val is not None and val != UNSET_SENTINEL:
                result[k] = val
            # Make "not k in optional_fields" into "k not in optional_fields" for speed
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                result[k] = val

        return result
