"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class DocumentUpdateInTypedDict(TypedDict):
    name: NotRequired[Nullable[str]]


class DocumentUpdateIn(BaseModel):
    name: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"name"}
        nullable_fields = {"name"}
        null_default_fields = set()

        serialized = handler(self)

        m = {}

        fields_set = self.__pydantic_fields_set__  # pylint: disable=no-member
        model_fields = type(self).model_fields

        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            # Remove key from serialized only if it exists
            if k in serialized:
                serialized.pop(k)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = n in fields_set or k in null_default_fields

            # Fast identity checks and value checks
            if val is not None and val is not UNSET_SENTINEL:
                m[k] = val
            elif val is not UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
