"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class EventOutTypedDict(TypedDict):
    name: str
    r"""The name of the event."""
    created_at: int
    r"""The UNIX timestamp (in seconds) of the event."""
    data: NotRequired[Nullable[Dict[str, Any]]]


class EventOut(BaseModel):
    name: str
    r"""The name of the event."""

    created_at: int
    r"""The UNIX timestamp (in seconds) of the event."""

    data: OptionalNullable[Dict[str, Any]] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Constants as sets for faster lookup
        optional_fields = {"data"}
        nullable_fields = {"data"}
        null_default_fields = set()

        serialized = handler(self)

        # Pre-calculate model fields and fields set once
        model_fields = type(self).model_fields
        fields_set = self.__pydantic_fields_set__

        m = {}

        # Avoid repeatedly popping from serialized, just consume keys as we use them
        # This avoids .pop from a possibly expensive dict operation
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = n in fields_set or k in null_default_fields  # pylint: disable=no-member

            # Fastest check: minimize branch depth, avoid repeated checks
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL:
                # not k in optional_fields is faster as k in set
                if (k not in optional_fields) or (optional_nullable and is_set):
                    m[k] = val

        return m
