"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


GithubRepositoryOutType = Literal["github"]


class GithubRepositoryOutTypedDict(TypedDict):
    name: str
    owner: str
    commit_id: str
    type: NotRequired[GithubRepositoryOutType]
    ref: NotRequired[Nullable[str]]
    weight: NotRequired[float]


class GithubRepositoryOut(BaseModel):
    name: str

    owner: str

    commit_id: str

    type: Optional[GithubRepositoryOutType] = "github"

    ref: OptionalNullable[str] = UNSET

    weight: Optional[float] = 1

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"type", "ref", "weight"}
        nullable_fields = {"ref"}
        null_default_fields = set()

        serialized = handler(self)
        m = {}

        # Precompute fields-set, avoids repeated .intersection calls
        fields_set = self.__pydantic_fields_set__

        # Cache fields for efficiency
        model_fields_items = type(self).model_fields.items()

        for n, f in model_fields_items:
            k = f.alias or n
            # Prefer .pop over .get/pop - single lookup
            val = serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (n in fields_set) or (k in null_default_fields)  # pylint: disable=no-member

            # Avoid repeated checks and branch lookups
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
