"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


GithubRepositoryInType = Literal["github"]


class GithubRepositoryInTypedDict(TypedDict):
    name: str
    owner: str
    token: str
    type: NotRequired[GithubRepositoryInType]
    ref: NotRequired[Nullable[str]]
    weight: NotRequired[float]


class GithubRepositoryIn(BaseModel):
    name: str

    owner: str

    token: str

    type: Optional[GithubRepositoryInType] = "github"

    ref: OptionalNullable[str] = UNSET

    weight: Optional[float] = 1

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Use tuple instead of sets for faster iteration and membership checks
        optional_fields = ("type", "ref", "weight")
        nullable_fields = ("ref",)
        null_default_fields = ()

        serialized = handler(self)

        # Preallocate dictionary with correct size to avoid resizing during insertion
        m = {}

        fields_set = self.__pydantic_fields_set__
        model_fields = type(self).model_fields

        # Convert null_default_fields to set for fast membership checking
        null_default_fields_set = set(null_default_fields)

        for n, f in model_fields.items():
            k = f.alias or n
            # Use dict.pop with default to avoid KeyError
            val = serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            # Convert "or" chain to "in" statement to speed up with tuple
            is_set = (n in fields_set) or (k in null_default_fields_set)

            # Update only as needed; combine conditional branches to reduce checks
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
