"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class ImageURLTypedDict(TypedDict):
    url: str
    detail: NotRequired[Nullable[str]]


class ImageURL(BaseModel):
    url: str

    detail: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"detail"}
        nullable_fields = {"detail"}
        null_default_fields = set()

        serialized = handler(self)

        m = {}

        # Cache fields_set for faster lookup, since intersection is O(n)
        fields_set = self.__pydantic_fields_set__

        # Use .items() directly for iterating, and avoid repeated lookups
        model_fields = type(self).model_fields
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = n in fields_set or k in null_default_fields  # pylint: disable=no-member

            # Avoid using pop here as we never use serialized again and pop causes unnecessary internal work.
            # Fast branch ordering for common cases (most keys are not UNSET_SENTINEL).
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
