"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class JobMetadataOutTypedDict(TypedDict):
    expected_duration_seconds: NotRequired[Nullable[int]]
    cost: NotRequired[Nullable[float]]
    cost_currency: NotRequired[Nullable[str]]
    train_tokens_per_step: NotRequired[Nullable[int]]
    train_tokens: NotRequired[Nullable[int]]
    data_tokens: NotRequired[Nullable[int]]
    estimated_start_time: NotRequired[Nullable[int]]


class JobMetadataOut(BaseModel):
    expected_duration_seconds: OptionalNullable[int] = UNSET

    cost: OptionalNullable[float] = UNSET

    cost_currency: OptionalNullable[str] = UNSET

    train_tokens_per_step: OptionalNullable[int] = UNSET

    train_tokens: OptionalNullable[int] = UNSET

    data_tokens: OptionalNullable[int] = UNSET

    estimated_start_time: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # The lists are used for fast lookup, so convert to set for O(1) "in"
        optional_fields = {
            "expected_duration_seconds",
            "cost",
            "cost_currency",
            "train_tokens_per_step",
            "train_tokens",
            "data_tokens",
            "estimated_start_time",
        }
        nullable_fields = optional_fields
        null_default_fields = set()

        serialized = handler(self)

        m = {}

        fields_set = self.__pydantic_fields_set__  # Cache the attribute lookup
        model_fields = type(self).model_fields  # Cache the attribute lookup

        # Avoid repeated lookup of keys: use .items() directly
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            # Instead of .pop for each field (costly as dict shrinks), only use .get

            optional_nullable = k in optional_fields  # Using sets, both are the same
            # Fast branch: intersection for one element is same as n in fields_set
            is_set = n in fields_set or k in null_default_fields  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
