"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class JobMetadataOutTypedDict(TypedDict):
    expected_duration_seconds: NotRequired[Nullable[int]]
    cost: NotRequired[Nullable[float]]
    cost_currency: NotRequired[Nullable[str]]
    train_tokens_per_step: NotRequired[Nullable[int]]
    train_tokens: NotRequired[Nullable[int]]
    data_tokens: NotRequired[Nullable[int]]
    estimated_start_time: NotRequired[Nullable[int]]


class JobMetadataOut(BaseModel):
    expected_duration_seconds: OptionalNullable[int] = UNSET

    cost: OptionalNullable[float] = UNSET

    cost_currency: OptionalNullable[str] = UNSET

    train_tokens_per_step: OptionalNullable[int] = UNSET

    train_tokens: OptionalNullable[int] = UNSET

    data_tokens: OptionalNullable[int] = UNSET

    estimated_start_time: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Precompute sets for fast lookups
        optional_fields = {
            "expected_duration_seconds",
            "cost",
            "cost_currency",
            "train_tokens_per_step",
            "train_tokens",
            "data_tokens",
            "estimated_start_time",
        }
        nullable_fields = (
            optional_fields  # The lists are the same, so we can use the same set
        )
        null_default_fields = set()

        serialized = handler(self)

        m = {}
        # Precompute the intersection set once for all fields
        fields_set = self.__pydantic_fields_set__  # pylint: disable=no-member

        # Avoid repeatedly calling type(self).model_fields: assign once
        model_fields = type(self).model_fields

        # Convert only once, and store local aliases for use in loop
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            # Instead of pop(), which is O(1) but mutates dict and not needed, use get()

            # Fast path: skip computing optional_nullable unless needed
            optional_nullable = (
                k in optional_fields
            )  # already equals k in nullable_fields
            is_set = (n in fields_set) or (k in null_default_fields)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
