"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class LibraryInTypedDict(TypedDict):
    name: str
    description: NotRequired[Nullable[str]]
    chunk_size: NotRequired[Nullable[int]]


class LibraryIn(BaseModel):
    name: str

    description: OptionalNullable[str] = UNSET

    chunk_size: OptionalNullable[int] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # These are constant lists, so turn them into sets for O(1) lookups
        optional_fields = {"description", "chunk_size"}
        nullable_fields = {"description", "chunk_size"}
        null_default_fields = set()

        serialized = handler(self)

        m = {}
        # Cache fields_set for reuse
        fields_set = self.__pydantic_fields_set__

        model_fields = type(self).model_fields
        for n, f in model_fields.items():
            k = f.alias or n
            # Use pop with default to avoid two dict lookups
            val = serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = n in fields_set or k in null_default_fields  # pylint: disable=no-member

            # The conditions below are preserved as in original logic
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
