"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class LibraryInUpdateTypedDict(TypedDict):
    name: NotRequired[Nullable[str]]
    description: NotRequired[Nullable[str]]


class LibraryInUpdate(BaseModel):
    name: OptionalNullable[str] = UNSET

    description: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"name", "description"}
        nullable_fields = optional_fields
        null_default_fields = set()

        serialized = handler(self)

        m = {}
        model_fields = type(self).model_fields

        # Precompute __pydantic_fields_set__ intersection for all n in advance
        pydantic_fields_set = self.__pydantic_fields_set__

        for n, f in model_fields.items():
            k = f.alias or n

            # Pop the value only once, this avoids double lookups
            val = serialized.pop(k, None)

            optional_nullable = k in optional_fields  # k in both sets
            is_set = (n in pydantic_fields_set) or (k in null_default_fields)  # pylint: disable=no-member

            # Fast common branch first; avoids unnecessary second branch for most normal cases
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
