"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class LibraryInUpdateTypedDict(TypedDict):
    name: NotRequired[Nullable[str]]
    description: NotRequired[Nullable[str]]


class LibraryInUpdate(BaseModel):
    name: OptionalNullable[str] = UNSET

    description: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"name", "description"}  # use set for O(1) lookup
        nullable_fields = optional_fields
        null_default_fields = set()

        serialized = handler(self)

        m = {}

        # Precompute intersection to avoid repeated set intersection cost
        fields_set = self.__pydantic_fields_set__

        # Avoid repeated lookups with local model_fields variable
        model_fields = type(self).model_fields

        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = (
                k in optional_fields
            )  # sets used so intersection with nullable_fields is superfluous
            is_set = n in fields_set or k in null_default_fields  # pylint: disable=no-member

            # Fast path: check for not None and not UNSET_SENTINEL first
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
