"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class MetricOutTypedDict(TypedDict):
    r"""Metrics at the step number during the fine-tuning job. Use these metrics to assess if the training is going smoothly (loss should decrease, token accuracy should increase)."""

    train_loss: NotRequired[Nullable[float]]
    valid_loss: NotRequired[Nullable[float]]
    valid_mean_token_accuracy: NotRequired[Nullable[float]]


class MetricOut(BaseModel):
    r"""Metrics at the step number during the fine-tuning job. Use these metrics to assess if the training is going smoothly (loss should decrease, token accuracy should increase)."""

    train_loss: OptionalNullable[float] = UNSET

    valid_loss: OptionalNullable[float] = UNSET

    valid_mean_token_accuracy: OptionalNullable[float] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Move repeated lists outside the loop to avoid recreating them each time
        optional_fields = {"train_loss", "valid_loss", "valid_mean_token_accuracy"}
        nullable_fields = optional_fields  # they are the same elements, so re-use reference
        null_default_fields = set()

        serialized = handler(self)
        m = {}

        # Pre-resolve fields and alias map to avoid repeated attribute access and lookups
        fields = type(self).model_fields

        # Precompute intersection for __pydantic_fields_set__ once
        fields_set = self.__pydantic_fields_set__

        for n, f in fields.items():
            k = f.alias or n
            val = serialized.pop(k, None)  # pop() returns value & removes key if present

            optional_nullable = k in optional_fields  # and k in nullable_fields (always true: sets are equal)
            is_set = (n in fields_set) or (k in null_default_fields)  # using 'in' for O(1)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (k not in optional_fields or (optional_nullable and is_set)):
                m[k] = val

        return m
