"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class OCRImageObjectTypedDict(TypedDict):
    id: str
    r"""Image ID for extracted image in a page"""
    top_left_x: Nullable[int]
    r"""X coordinate of top-left corner of the extracted image"""
    top_left_y: Nullable[int]
    r"""Y coordinate of top-left corner of the extracted image"""
    bottom_right_x: Nullable[int]
    r"""X coordinate of bottom-right corner of the extracted image"""
    bottom_right_y: Nullable[int]
    r"""Y coordinate of bottom-right corner of the extracted image"""
    image_base64: NotRequired[Nullable[str]]
    r"""Base64 string of the extracted image"""
    image_annotation: NotRequired[Nullable[str]]
    r"""Annotation of the extracted image in json str"""


class OCRImageObject(BaseModel):
    id: str
    r"""Image ID for extracted image in a page"""

    top_left_x: Nullable[int]
    r"""X coordinate of top-left corner of the extracted image"""

    top_left_y: Nullable[int]
    r"""Y coordinate of top-left corner of the extracted image"""

    bottom_right_x: Nullable[int]
    r"""X coordinate of bottom-right corner of the extracted image"""

    bottom_right_y: Nullable[int]
    r"""Y coordinate of bottom-right corner of the extracted image"""

    image_base64: OptionalNullable[str] = UNSET
    r"""Base64 string of the extracted image"""

    image_annotation: OptionalNullable[str] = UNSET
    r"""Annotation of the extracted image in json str"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Precompute sets for fast membership tests
        optional_fields_set = {"image_base64", "image_annotation"}
        nullable_fields_set = {
            "top_left_x",
            "top_left_y",
            "bottom_right_x",
            "bottom_right_y",
            "image_base64",
            "image_annotation",
        }
        null_default_fields_set = set()

        # Handler is called once up front (no change)
        serialized = handler(self)

        # Pre-fetch fields for efficiency
        model_fields = type(self).model_fields
        field_set = self.__pydantic_fields_set__
        m = {}

        # Loop using local variables for fast lookup, avoid repeated lookups
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.pop(k, None)  # Pop here to avoid double dict lookup

            optional_nullable = k in optional_fields_set and k in nullable_fields_set
            # Intersection returns a set; check if non-empty for is_set
            # Optimize by not actually producing the intersection set object
            is_set = (n in field_set) or (k in null_default_fields_set)  # pylint: disable=no-member

            # Avoid repeated "val is not None" and "val != UNSET_SENTINEL" checks where possible
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields_set or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
