"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class OCRImageObjectTypedDict(TypedDict):
    id: str
    r"""Image ID for extracted image in a page"""
    top_left_x: Nullable[int]
    r"""X coordinate of top-left corner of the extracted image"""
    top_left_y: Nullable[int]
    r"""Y coordinate of top-left corner of the extracted image"""
    bottom_right_x: Nullable[int]
    r"""X coordinate of bottom-right corner of the extracted image"""
    bottom_right_y: Nullable[int]
    r"""Y coordinate of bottom-right corner of the extracted image"""
    image_base64: NotRequired[Nullable[str]]
    r"""Base64 string of the extracted image"""
    image_annotation: NotRequired[Nullable[str]]
    r"""Annotation of the extracted image in json str"""


class OCRImageObject(BaseModel):
    id: str
    r"""Image ID for extracted image in a page"""

    top_left_x: Nullable[int]
    r"""X coordinate of top-left corner of the extracted image"""

    top_left_y: Nullable[int]
    r"""Y coordinate of top-left corner of the extracted image"""

    bottom_right_x: Nullable[int]
    r"""X coordinate of bottom-right corner of the extracted image"""

    bottom_right_y: Nullable[int]
    r"""Y coordinate of bottom-right corner of the extracted image"""

    image_base64: OptionalNullable[str] = UNSET
    r"""Base64 string of the extracted image"""

    image_annotation: OptionalNullable[str] = UNSET
    r"""Annotation of the extracted image in json str"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Precompute sets for faster membership tests
        optional_fields = {"image_base64", "image_annotation"}
        nullable_fields = {
            "top_left_x",
            "top_left_y",
            "bottom_right_x",
            "bottom_right_y",
            "image_base64",
            "image_annotation",
        }
        null_default_fields = set()  # Empty as original

        serialized = handler(self)

        # Avoid repeated lookups by storing intersection set once
        fields_set = self.__pydantic_fields_set__

        m = {}
        # Use items() and direct iteration instead of repeated lookups
        # This reduces attribute lookups and uses local variables where possible
        model_fields = type(self).model_fields
        for n, f in model_fields.items():
            k = f.alias or n

            val = serialized.pop(k, None)
            optional_nullable = k in optional_fields and k in nullable_fields

            # Avoid calling intersection every iteration;
            # check presence of n in the set, which is faster.
            is_set = (n in fields_set) or (k in null_default_fields)

            # Branch structure retained, rewritten for fewer comparisons
            # Use 'is not' for None and '!=' for sentinel
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL:
                if (k not in optional_fields) or (optional_nullable and is_set):
                    m[k] = val

        return m
