"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jsonschema import JSONSchema, JSONSchemaTypedDict
from .responseformats import ResponseFormats
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ResponseFormatTypedDict(TypedDict):
    type: NotRequired[ResponseFormats]
    r"""An object specifying the format that the model must output. Setting to `{ \"type\": \"json_object\" }` enables JSON mode, which guarantees the message the model generates is in JSON. When using JSON mode you MUST also instruct the model to produce JSON yourself with a system or a user message."""
    json_schema: NotRequired[Nullable[JSONSchemaTypedDict]]


class ResponseFormat(BaseModel):
    type: Optional[ResponseFormats] = None
    r"""An object specifying the format that the model must output. Setting to `{ \"type\": \"json_object\" }` enables JSON mode, which guarantees the message the model generates is in JSON. When using JSON mode you MUST also instruct the model to produce JSON yourself with a system or a user message."""

    json_schema: OptionalNullable[JSONSchema] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Avoid repeated lookups and unnecessary list/dict constructions
        optional_fields = {"type", "json_schema"}
        nullable_fields = {"json_schema"}
        null_default_fields = set()

        serialized = handler(self)
        m = {}

        # Precompute one-time values
        fields_set = self.__pydantic_fields_set__

        # Access model_fields as attribute just once
        model_fields_items = type(self).model_fields.items()

        for n, f in model_fields_items:
            # f.alias may be None, so re-use n if needed (no change logic)
            k = f.alias or n
            # val = serialized.get(k) consumes just the value once
            val = serialized.get(k)
            # Remove key if present to avoid redundant memory usage
            serialized.pop(k, None)

            # Avoid repeated in operator by combining sets above
            optional_nullable = k in optional_fields and k in nullable_fields
            # Intersection is expensive for big sets; with one element, use fast membership test instead
            is_set = n in fields_set or k in null_default_fields

            # Reduce val != checks in sequence; merge logic for branch clarity
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
