"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class SharingOutTypedDict(TypedDict):
    library_id: str
    org_id: str
    role: str
    share_with_type: str
    share_with_uuid: str
    user_id: NotRequired[Nullable[str]]


class SharingOut(BaseModel):
    library_id: str

    org_id: str

    role: str

    share_with_type: str

    share_with_uuid: str

    user_id: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"user_id"}
        nullable_fields = optional_fields  # Both refer to the same field
        null_default_fields = set()  # No need for a list if always empty

        serialized = handler(self)
        m = {}

        # Precompute values for efficiency
        model_fields_items = type(self).model_fields.items()
        fields_set = self.__pydantic_fields_set__
        serialized_pop = serialized.pop

        for n, f in model_fields_items:
            k = f.alias or n
            val = serialized.get(k)
            serialized_pop(k, None)

            is_optional = k in optional_fields
            is_nullable = is_optional  # always the same field(s) in current logic
            optional_nullable = is_optional and is_nullable
            is_set = (n in fields_set) or (
                k in null_default_fields
            )  # Using 'in' is cheaper than set.intersection

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not is_optional or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
