"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class SharingOutTypedDict(TypedDict):
    library_id: str
    org_id: str
    role: str
    share_with_type: str
    share_with_uuid: str
    user_id: NotRequired[Nullable[str]]


class SharingOut(BaseModel):
    library_id: str

    org_id: str

    role: str

    share_with_type: str

    share_with_uuid: str

    user_id: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {"user_id"}
        nullable_fields = {"user_id"}
        null_default_fields = set()

        serialized = handler(self)
        m = {}
        model_fields = type(self).model_fields
        fields_set = self.__pydantic_fields_set__

        # Precompute sets and checks for efficiency.
        # No need to recompute per-field intersections/containment.
        optional_nullable_fields = optional_fields & nullable_fields

        for n, f in model_fields.items():
            k = f.alias or n

            # Combined pop/get for speed and clarity
            val = serialized.pop(k, None)

            # Only need to check if the field was set or belongs to null_default_fields
            is_set = (n in fields_set) or (k in null_default_fields)

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (k in optional_nullable_fields and is_set)
            ):
                m[k] = val

        return m
