"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class UpdateFTModelInTypedDict(TypedDict):
    name: NotRequired[Nullable[str]]
    description: NotRequired[Nullable[str]]


class UpdateFTModelIn(BaseModel):
    name: OptionalNullable[str] = UNSET

    description: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Convert lists to sets for O(1) membership tests
        optional_fields = {"name", "description"}
        nullable_fields = {"name", "description"}
        null_default_fields = set()

        serialized = handler(self)

        m = {}

        # Cache intersection method and field values for performance
        fields_set = self.__pydantic_fields_set__

        # Avoid repeated lookups in loop
        model_fields_items = type(self).model_fields.items()

        for n, f in model_fields_items:
            k = f.alias or n
            # Use get and pop only once
            val = serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            # Use set intersection directly on k
            is_set = n in fields_set or k in null_default_fields  # pylint: disable=no-member

            # Reduce number of comparisons and branches
            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
