"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class UsageInfoTypedDict(TypedDict):
    prompt_tokens: NotRequired[int]
    completion_tokens: NotRequired[int]
    total_tokens: NotRequired[int]
    prompt_audio_seconds: NotRequired[Nullable[int]]


class UsageInfo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    prompt_tokens: Optional[int] = 0

    completion_tokens: Optional[int] = 0

    total_tokens: Optional[int] = 0

    prompt_audio_seconds: OptionalNullable[int] = UNSET

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = {
            "prompt_tokens",
            "completion_tokens",
            "total_tokens",
            "prompt_audio_seconds",
        }
        nullable_fields = {"prompt_audio_seconds"}
        null_default_fields = set()

        serialized = handler(self)
        m = {}

        self_fields_set = self.__pydantic_fields_set__
        model_fields = type(self).model_fields

        # Precompute set intersection for optional_nullable and is_set
        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            # Avoid constructing a new set for every field
            is_set = n in self_fields_set or k in null_default_fields  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        # Only need to update with remaining serialized items as .pop() removed processed keys
        # (no duplicate keys to worry about)
        if serialized:
            m.update(serialized)

        return m
