"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mistralai.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


WandbIntegrationOutType = Literal["wandb"]


class WandbIntegrationOutTypedDict(TypedDict):
    project: str
    r"""The name of the project that the new run will be created under."""
    type: NotRequired[WandbIntegrationOutType]
    name: NotRequired[Nullable[str]]
    r"""A display name to set for the run. If not set, will use the job ID as the name."""
    run_name: NotRequired[Nullable[str]]
    url: NotRequired[Nullable[str]]


class WandbIntegrationOut(BaseModel):
    project: str
    r"""The name of the project that the new run will be created under."""

    type: Optional[WandbIntegrationOutType] = "wandb"

    name: OptionalNullable[str] = UNSET
    r"""A display name to set for the run. If not set, will use the job ID as the name."""

    run_name: OptionalNullable[str] = UNSET

    url: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        # Optimize repeated container creation & lookup, remove unnecessary pop from dict
        # Precompute sets for faster membership checks
        optional_fields_set = {"type", "name", "run_name", "url"}
        nullable_fields_set = {"name", "run_name", "url"}
        # null_default_fields was always empty, so can be removed and simplify checks

        serialized = handler(self)
        m = {}

        # Use local references to avoid repeated global lookup
        model_fields = type(self).model_fields
        fields_set = self.__pydantic_fields_set__

        for n, f in model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            # Compute flags with set logic
            optional_nullable = k in optional_fields_set and k in nullable_fields_set
            is_set = n in fields_set  # intersection{n} is equivalent to membership

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                k not in optional_fields_set or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
